version: "3.8"
services:
    web:
        build: ./web
        container_name: web
        ports:
            - "9000:9000"
        volumes:
            - ./web:/usr/src/app:rw
    proxy:
        build: ./proxy
        container_name: proxy
        ports:
            - "3000:3000"
        volumes:
            - ./proxy:/usr/src/app:rw
    db:
        image: bitnami/couchdb:3.1.0
        restart: always
        container_name: db
        env_file:
            - .env
