web:
    build: ./web
    ports:
        - "9000:9000"
    volumes:
        - ./web:/usr/src/app:rw

proxy:
    build: ./proxy
    ports:
        - "3000:3000"
    volumes:
        - ./proxy:/usr/src/app:rw
